spring.application.name=api-gateway
server.port=5000

#Configuración de la ruta del servicio de productos
spring.cloud.gateway.routes[0].id=productos-service
spring.cloud.gateway.routes[0].uri=lb://productos-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/productos/**
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Gateway-Passed,true

#Configuración de la ruta del servicio de usuarios
spring.cloud.gateway.routes[1].id=usuarios-service
spring.cloud.gateway.routes[1].uri=lb://usuarios-service    
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/usuarios/**
spring.cloud.gateway.routes[1].filters[0]=AddRequestHeader=X-Gateway-Passed,true

#Configuración de la ruta del servicio de autenticación
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-service    
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[2].filters[0]=AddRequestHeader=X-Gateway-Passed,true

#Habilitar el descubrimiento automatico en eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#Configurar directorio de eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
