# DataSource - PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bdprueba
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

# Table names physically
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# App Properties 
bezkoder.app.jwtSecret= ==================claveSecreta======================
bezkoder.app.jwtExpirationMs=86400000

spring.application.name=auth-service
server.port=6000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG